import type { Metadata, Viewport } from 'next';
import './globals.css';
import '../styles/themes/light.css';
import '../styles/themes/dark.css';
import '../styles/tokens.css';
import './styles/theme.css';

import ClientRoot from './ClientRoot';
import GoogleAnalytics from './components/Analytics/GoogleAnalytics';
import {
  BASE_URL,
  SITE_NAME,
  SITE_DESCRIPTION,
  SITE_TAGLINE,
  buildWebSiteJsonLd,
  buildOrganizationJsonLd,
  buildSoftwareAppJsonLd,
  buildSiteNavigationJsonLd,
  buildAggregateRatingJsonLd,
  jsonLdScriptProps,
  SEO_KEYWORDS,
} from '../lib/seo';

// ── Structured data for Google rich results ──────────────────────────────
// 1. WebSite – Enables Sitelinks SearchBox in Google SERP
// 2. Organization – Shows brand Knowledge Panel with logo + social links
// 3. SoftwareApplication – App rich result with rating
// 4. SiteNavigationElement – Helps Google understand main nav for sitelinks
// 5. AggregateRating – Social proof in search results
const websiteJsonLd = buildWebSiteJsonLd();
const orgJsonLd = buildOrganizationJsonLd();
const appJsonLd = buildSoftwareAppJsonLd();
const navJsonLd = buildSiteNavigationJsonLd();
const ratingJsonLd = buildAggregateRatingJsonLd(0, 0);

// Flatten top keywords for root metadata (Semrush-validated, highest volume first)
const rootKeywords = [
  ...SEO_KEYWORDS.brand,
  ...SEO_KEYWORDS.transactional.slice(0, 12),
  ...SEO_KEYWORDS.informational.slice(0, 8),
  ...SEO_KEYWORDS.longTail.slice(0, 6),
  ...SEO_KEYWORDS.technology.slice(0, 4),
  ...SEO_KEYWORDS.features.slice(0, 4),
];

export const metadata: Metadata = {
  metadataBase: new URL(BASE_URL),
  title: {
    default: `${SITE_NAME} - Best Freelancer Website | Hire Freelance Developers, Designers & Experts Online`,
    template: `%s | ${SITE_NAME} - ${SITE_TAGLINE}`,
  },
  description: SITE_DESCRIPTION,
  keywords: rootKeywords,
  manifest: '/manifest.json',
  icons: {
    icon: [
      { url: '/icon.svg', type: 'image/svg+xml' },
      { url: '/icons/icon-144x144.png', sizes: '144x144', type: 'image/png' },
      { url: '/icons/icon-192x192.png', sizes: '192x192', type: 'image/png' },
      { url: '/icons/icon-192x192.svg', sizes: '192x192', type: 'image/svg+xml' },
      { url: '/icons/icon-512x512.svg', sizes: '512x512', type: 'image/svg+xml' },
    ],
    shortcut: '/icon.svg',
    apple: [
      { url: '/icons/icon-192x192.png', sizes: '180x180', type: 'image/png' },
    ],
  },
  authors: [{ name: 'MegiLance Team', url: 'https://megilance.com' }],
  creator: 'MegiLance',
  publisher: 'MegiLance',
  applicationName: 'MegiLance',
  category: 'Business',
  classification: 'Freelance Marketplace',
  referrer: 'origin-when-cross-origin',
  
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: BASE_URL,
    siteName: SITE_NAME,
    title: `${SITE_NAME} - Best Freelancer Website | Hire Top Freelancers Online`,
    description: 'Find freelance jobs online or hire top freelance web developers, designers & writers. AI-powered matching, zero commission, secure escrow payments. The #1 Upwork & Fiverr alternative for freelance work online.',
    countryName: 'Worldwide',
    // Images auto-generated by app/opengraph-image.tsx (Next.js file convention)
  },
  
  twitter: {
    card: 'summary_large_image',
    site: '@megilance',
    creator: '@megilance',
    title: `${SITE_NAME} - Best Freelancer Website | Freelance Jobs Online`,
    description: 'Hire freelance web developers, designers & writers online. Find freelance jobs with AI matching, zero commission & secure payments. Best Upwork & Fiverr alternative.',
    // Images auto-generated by app/twitter-image.tsx (Next.js file convention)
  },
  
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  
  verification: {
    google: process.env.GOOGLE_SITE_VERIFICATION,
    yandex: process.env.YANDEX_VERIFICATION,
    other: {
      'msvalidate.01': process.env.BING_VERIFICATION || '',
      'p:domain_verify': process.env.PINTEREST_VERIFICATION || '',
    },
  },
  
  alternates: {
    canonical: BASE_URL,
    languages: {
      'en-US': BASE_URL,
      'x-default': BASE_URL,
    },
  },
  
  other: {
    'msapplication-TileColor': '#4573df',
    'apple-mobile-web-app-capable': 'yes',
    'apple-mobile-web-app-status-bar-style': 'black-translucent',
    'apple-mobile-web-app-title': SITE_NAME,
    'format-detection': 'telephone=no',
    'mobile-web-app-capable': 'yes',
    'msapplication-config': '/browserconfig.xml',
    'theme-color': '#4573df',
  },
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
  userScalable: true,
  viewportFit: 'cover',
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#ffffff' },
    { media: '(prefers-color-scheme: dark)', color: '#0b0f19' },
  ],
  colorScheme: 'light dark',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Google Analytics - FREE forever */}
        <GoogleAnalytics />
        
        {/* Preconnect to important third-party origins */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        
        {/* DNS prefetch for API */}
        <link rel="dns-prefetch" href="//api.stripe.com" />
        
        {/* RSS Feed for Blog - improves content discovery by search engines */}
        <link rel="alternate" type="application/rss+xml" title="MegiLance Blog" href="/blog/feed.xml" />
        
        {/* Structured Data for SEO – Google Rich Results */}
        <script {...jsonLdScriptProps(websiteJsonLd)} />
        <script {...jsonLdScriptProps(orgJsonLd)} />
        <script {...jsonLdScriptProps(appJsonLd)} />
        <script {...jsonLdScriptProps(navJsonLd)} />
        <script {...jsonLdScriptProps(ratingJsonLd)} />
        
        {/* Theme initialization - prevent flash */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var theme = localStorage.getItem('megilance-theme');
                  if (!theme) {
                    theme = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
                  }
                  document.documentElement.classList.add(theme);
                  document.documentElement.style.colorScheme = theme;
                } catch (e) {}
              })();
            `,
          }}
        />
        {/* Mobile sidebar fix - inject style to override Turbopack phantom animation */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                var s = document.createElement('style');
                s.textContent = '@media(max-width:768px){aside[class*="sidebar"]:not([class*="sidebarNav"]){display:none!important;animation:none!important}aside[class*="sidebar"][class*="sidebarMobileOpen"]{display:flex!important;animation:none!important;transform:translateX(0)!important;position:fixed!important;z-index:1000!important}aside[class*="sidebarMobileOpen"] aside{display:block!important}}';
                document.head.appendChild(s);
              })();
            `,
          }}
        />
      </head>
      <body className="bg-[var(--background)] text-[var(--text-primary)] antialiased">
        <ClientRoot>
          {children}
        </ClientRoot>
      </body>
    </html>
  );
}

